export {default as Login} from "./Login/Login";
export {default as AdminLogin} from "./Login/AdminLogin";
export {default as Signup} from "./Signup/Signup"
export {default as PersonalDetails} from "./PersonalDetails/PersonalDetails"
export {default as MyWishList} from "./WishList/MyWishList"
export {default as WishList} from "./WishList/WishList"
export {default as SearchWishList} from "./WishList/SearchWishList"
export {default as ManageAdmins} from "./SuperAdmin/ManageAdmins"
export {default as WishListReport} from "./Admin/WishListReport"